### ISSUE TITLE
1.6.0: `gulp icons` crashes, Gulp 3 incompatible with Node 12

### ISSUE THREAD

**Issue by lkraav** [vaadin/vaadin-lumo-styles#85]
```sh
leho@papaya vaadin-lumo-styles $ [git:master] npx gulp icons
fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/home/leho/Documents/web-components/vaadin-lumo-styles/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/leho/Documents/web-components/vaadin-lumo-styles/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/leho/Documents/web-components/vaadin-lumo-styles/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
```

See

* https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node
* https://github.com/gulpjs/gulp/issues/2324

**Comment by lkraav** [comment]
After `npm install gulp@^4`, I think `gulp icons` fails to work without additional help:

```
$ [git:master+] ./node_modules/.bin/gulp icons
assert.js:385
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/leho/Documents/web-components/vaadin-lumo-styles/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/leho/Documents/web-components/vaadin-lumo-styles/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/leho/Documents/web-components/vaadin-lumo-styles/gulpfile.js:14:6)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at execute (/home/leho/Documents/web-components/vaadin-lumo-styles/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by lkraav** [comment]
https://stackoverflow.com/questions/51098749/everytime-i-run-gulp-anything-i-get-a-assertion-error-task-function-must-be seems to apply.

**Comment by lkraav** [comment]
While I have Gulpfile now working with Gulp 4, I can see PR to this probably has to work with https://github.com/vaadin/vaadin-component-dev-dependencies/pull/3
